### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by scharph** [aduskett/docker-mcuxpresso#2]
after `docker-compose up` up i got this
```mcuexpresso-dev    | No protocol specified
mcuexpresso-dev    | Unable to init server: Could not connect: Connection refused
mcuexpresso-dev    | Mcuxpressoide: Cannot open display: 
mcuexpresso-dev    | No protocol specified
mcuexpresso-dev    | Unable to init server: Could not connect: Connection refused
mcuexpresso-dev    | Mcuxpressoide: Cannot open display: 
mcuexpresso-dev    | Mcuxpressoide:
mcuexpresso-dev    | An error has occurred. See the log file
mcuexpresso-dev    | /usr/local/mcuxpressoide-11.3.1_5262/ide/configuration/1620638923014.log.
```
the written logfile: 

```log
!SESSION 2021-05-10 09:28:42.929 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_265
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2021-05-10 09:28:43.201
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
philipp@debian:~/development/engel/docker-mcuxpresso$ 
```

docker-compose file
```yaml
version: "3.7"
services:
   mcuexpresso-dev:
    build:
      context: ./
      args:
       # Customize your IDE version here
       IDE_VERSION: 11.3.1_5262
       USERNAME: root
       UID: 1000
       GID: 1000
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=unix:0
    volumes:
      - ./:/mnt
      # dbus
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/machine-id:/var/lib/dbus/machine-id
      - /var/run/dbus:/var/run/dbus
      # X11 Forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./log:/usr/local/mcuxpressoide-11.3.1_5262/ide/configuration
    image: mcuexpresso-dev:latest
    container_name:  mcuexpresso-dev
```
DISPLAY of host
```shell
echo $DISPLAY
:0
```

Linux debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

any idea what i am doing wrong?

**Comment by aduskett** [comment]
The username has to match your currently logged-in username. I doubt you are normally logged in as root :)

**Comment by scharph** [comment]
got it running

had to add this in the dockerfile
`RUN adduser ${USERNAME}` before line 34

without that, it couldnt find my user

**Comment by aduskett** [comment]
Sorry about that! I pushed a fix!
